tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'jawshooah/pyenv'
tap 'peco/peco'
tap 'sanemat/font'
tap 'tcnksm/ghr'
cask 'xquartz'
brew 'ansifilter'
brew 'autoconf'
brew 'xz'
brew 'automake'
brew 'awscli'
brew 'pkg-config'
brew 'bdw-gc'
brew 'c-ares'
brew 'libpng', args: ['universal']
brew 'freetype', args: ['universal']
brew 'fontconfig', args: ['universal']
brew 'pixman'
brew 'gettext'
brew 'libffi'
brew 'glib'
brew 'cairo'
brew 'pcre'
brew 'git'
brew 'go'
brew 'ccat'
brew 'cmake'
brew 'clang-format'
brew 'gmp'
brew 'coreutils'
brew 'ctags'
brew 'makedepend'
brew 'openssl', args: ['universal']
brew 'libssh2'
brew 'curl'
brew 'libsodium'
brew 'zeromq'
brew 'czmq'
brew 'd-bus'
brew 'direnv'
brew 'docker'
brew 'libyaml'
brew 'docker-machine'
brew 'docker-compose'
brew 'libtool', args: ['universal']
brew 'unixodbc'
brew 'jpeg', args: ['universal']
brew 'libtiff', args: ['universal']
brew 'wxmac'
brew 'erlang'
brew 'elixir'
brew 'gobject-introspection'
brew 'icu4c'
brew 'harfbuzz'
brew 'pango'
brew 'fontforge'
brew 'gd', args: ['universal']
brew 'gdbm'
brew 'geoip'
brew 'gibo'
brew 'gnupg'
brew 'libtasn1', args: ['universal']
brew 'nettle'
brew 'gnutls'
brew 'libgpg-error'
brew 'libgcrypt'
brew 'libksba'
brew 'libassuan'
brew 'pth'
brew 'pinentry'
brew 'gpg-agent'
brew 'htop-osx'
brew 'hub'
brew 'jasper', args: ['universal']
brew 'oniguruma'
brew 'jq'
brew 'keychain'
brew 'libevent'
brew 'libusb', args: ['universal']
brew 'libusb-compat', args: ['universal']
brew 'libgphoto2', args: ['universal']
brew 'libicns', args: ['universal']
brew 'libpcl'
brew 'libxml2'
brew 'libxslt'
brew 'little-cms2', args: ['universal']
brew 'llvm'
brew 'lua'
brew 'mercurial'
brew 'mysql'
brew 'nkf'
brew 'nodebrew'
brew 'packer'
brew 'peco'
brew 'phantomjs'
brew 'pinentry-mac'
brew 'readline'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'pyenv-virtualenvwrapper'
brew 'qt'
brew 'ruby-build'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'rbenv-gemset'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'sane-backends', args: ['universal']
brew 'sqlite'
brew 'ssh-copy-id'
brew 'terminal-notifier'
brew 'terraform'
brew 'tig'
brew 'tmux'
brew 'v8'
brew 'vim', args: ['with-lua']
brew 'w3m'
brew 'watch'
brew 'wget'
brew 'wine'
brew 'wireshark', args: ['with-qt']
brew 'zsh'
brew 'homebrew/dupes/unzip'
brew 'jawshooah/pyenv/pyenv-default-packages'
brew 'sanemat/font/ricty', args: ['powerline', 'vim-powerline']
brew 'tcnksm/ghr/ghr'
cask 'dash'
cask 'google-chrome'
cask 'keepassx'
cask 'licecap'
cask 'mysqlworkbench'
cask 'nylas-n1'
cask 'skype'
cask 'typora'
cask 'vagrant'
cask 'virtualbox'
